run: mytraceroute_19CS10069_19CS30007.c
	cc -o tracer mytraceroute_19CS10069_19CS30007.c
	sudo ./tracer cse.iitkgp.ac.in 2> error.log

play: play.c
	cc -o play play.c
	./play
	
clean:
	rm -f tracer play ref
